app:
  name: ui
  image:
    repository: onecx/onecx-tenant-ui
  routing:
    enabled: true
    path: /mfe/tenant/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OneCXTenantModule'
          description: 'OneCX Tenant UI'
          note: 'OneCX OneCXTenant UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-tenant
          tagName: ocx-tenant-component
    permission:
      enabled: true
      spec:
        permissions:
          TENANT:
            CREATE: Create tenant
            EDIT: Edit tenant
            DELETE: Delete tenant
            SAVE: Update and save tenant
            VIEW: View mode for tenant
            SEARCH: Search tenant
            USE_SEARCHCONFIGS: Use search configs in tenant
